### ISSUE TITLE
Problems loading module and defining animated components (Newbie).

### ISSUE THREAD

**Issue by camerow** [elierotenberg/react-animate#10]
Trying to get this going in a project and running into some problems. If I use your example of:

``` js
Animate.extend(class MyComponent extends React.Component {
  fadeIn() {
    // syntax using call delegation
    Animate.animate.call(this,
      'my-custom-animation', // animation name
      { opacity: 0 }, // initial style
      { opacity: 1 }, // final style
      1000, // animation duration (in ms)
      { easing: 'linear' } // other options
    );
  }

  render() {
    return <div>
      <button onClick={this.fadeIn}>Click to fade in</button>
      <div style={Animate.getAnimatedStyle.call(this, 'my-custom-animation')}>
        This text will appear soon after the click.
      </div>
    </div>;
  }
});
```

And use webpack babel loader to load your module: 

``` js
{
    test: /\.jsx?$/,
    loader: "babel?stage=0?includePaths[]=node_modules/react-animate/src"
}
```

I get through compiling, but when `MyComponent` goes to render it is an undefined component. From there I also re-ran nodemon, and I get an _Unexpected reservered word_ Syntax error. 

``` sh
(function (exports, require, module, __filename, __dirname) { import raf from 
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .jsx] (/home/will/projects/zipwhip/verification-service/node_modules/babel-core/lib/api/register/node.js:214:7)
```

So I figure I'm probably using the webpack loader wrong. Any advice on this? Still learning Webpack build tool and es6/7 stuff. Thanks in advance!

**Comment by elierotenberg** [comment]
Do you add the jsx extension to the list of extensions resolved by webpack?

It should be something like that in your webpack config:

``` js
  resolve: {
    extensions: ['', '.js', '.jsx'],
  },
```

see http://webpack.github.io/docs/configuration.html#resolve-extensions

**Comment by camerow** [comment]
Yeah. I have that there. I've got lots of other jsx files and npm modules working fine. Just seem to be struggling with this one for some reason =/. Let me play a bit more and see if I can formulate a better question or description of my problem. 

Thanks for the help! This looks like an amazing module once I can get it up and running. _thumbsup_

**Comment by eTorAken** [comment]
Thanks to open a new issue if needed.
