### ISSUE TITLE
using in several components

### ISSUE THREAD

**Issue by DCrusher** [elierotenberg/react-animate#5]
Hi! Tell me, please, how you can use the react-animate in several independent (or subsidiaries) components simultaneously. Trying to load the module 'react-animate' using commonJS (require('react-animate')) in several react components. When page is loading, an error occurs in browser console: "Error: only one instance of babel/polyfill is allowed".

**Comment by elierotenberg** [comment]
Hi, I've used react-animated in multiple components without issues.

Whch module bundler do you use? Webpack, browserify?

If multiple versions of babel are present in your bundle, then it will be
bundled multiple times and generate this error. You may want to check in
your bundle output that babel is only present once.


Elie ROTENBERG  <http://static.mnium.org/images/signature/twt.png>
<http://static.mnium.org/images/signature/lkn.png>
<https://twitter.com/elierotenberg>
<https://www.linkedin.com/in/elierotenberg>[image:
https://github.com/elierotenberg] <https://github.com/elierotenberg>
<http://static.mnium.org/images/signature/lkn.png>CTO +33(0) 689 29 98 19
<callto:+33(0)%20621%2031%2040%2069>
 elie@rotenberg.ioAdresse : 3, avenue Hoche - 75008 Paris (Hall 1, Etage 5)

**Comment by DCrusher** [comment]
I'm creating react components in ruby on rails project using for this pupsposes gem 'react-rails'. As module bundler I'm using browserify. Сomplicated infrastructure browserify and sprockets (rails bundler) has generate a lot of duplicated code. This was the caused an error. The error not associated with the module 'react-animate'. Thank you for help.

**Comment by elierotenberg** [comment]
Cool :)
